### ISSUE TITLE
django-error.log should be in logs directory

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/partners.ubuntu.com#124]
The django-error.log file should be in /srv/ubuntu-partners-app-X/logs instead of /srv/ubuntu-partners-app-X/code/latest/

**Comment by pmahnke** [comment]
@nottrobin is this still relevant

**Comment by nottrobin** [comment]
Since moving partners to K8s (which would render this irrelevant) is on the roadmap for this cycle, I don't see us getting to this. I'll close it now.
