### ISSUE TITLE
On partners.ubuntu.com/hardware some logos are repeated AND the featured logo are not shown

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/partners.ubuntu.com#155]
## Summary
on https://partners.ubuntu.com/programmes/hardware 

## Process

Visit the  page and scroll to the "a selection of partners section"

## Current and expected result

Currently some partners are listed twice, while featured partners are not listed

## Screenshot

![image](https://user-images.githubusercontent.com/230348/40673562-0397aada-636a-11e8-835f-abcf49b2c211.png)

**Comment by anthonydillon** [comment]
Let's try and find out the reason for the duplication. There was should only be one entry in the database.

**Comment by anasereijo** [comment]
Just checked and it's not happening anymore (or I can't see it). This page was updated recently.
