### ISSUE TITLE
No explanation of coloured rings on retail partners map

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/partners.ubuntu.com#162]
1\. Go to [the “Ubuntu retail partners” page](https://partners.ubuntu.com/programmes/retail).
2\. Look at the map.

What you see:
- A mixture of purple, orange, and black rings.
- Nothing on the page that explains the different colours.
- No change when hovering or clicking.

![partners ubuntu com-retail-map](https://user-images.githubusercontent.com/19801137/44086059-4de948e8-9fb3-11e8-8ed3-b0f81855bb6b.png)

What you should see: either
- the rings are all the same colour; or
- a legend explains the different colours; or
- each ring explains its colour when hovered or clicked; or
- (least likely) the map no longer exists.

---
*Reported from: https://partners.ubuntu.com/programmes/retail*

**Comment by anthonydillon** [comment]
I think we should remove this image from this page.

**Comment by Greggless** [comment]
Can we change the list to be numbered, and update the rings accordingly?

**Comment by anasereijo** [comment]
@pmahnke do you think this is still worth doing as we will have partners under canonical.com? or will this page still exist anyway?

**Comment by anthonydillon** [comment]
@anasereijo this is still valid until we fix the issue or remove the map.

**Comment by pmahnke** [comment]
personally I don't see this as an issue, the bullets below serve as the legend

the colours are decoration, I think we can close this, specially knowing there are updates coming to this site in this next cycle.
