### ISSUE TITLE
Find a Partner shouldn't rely on JS-only functionality

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/partners.ubuntu.com#179]
## Summary

The "Find a partner" page relies on JavaScript and the JS code is dependant on deprecated YUI.

We should investigate replacing it with a server-side search (some of the functionality used for generating JSON feeds could be repurposed for this).

The frontend can then make use of JS but have a more robust no-JS fallback.

**Comment by pmahnke** [comment]
1. add u-hide to the filter
2. remove u-hide from list of partners
3. use js to reverse this on load
