### ISSUE TITLE
“Thank you!” page is visitable and shows up in search results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/partners.ubuntu.com#190]
The page “Thank you! We’re really excited about your interest in partnering with Ubuntu…”
- [is directly visitable](https://partners.ubuntu.com/thank-you?aliId=53425701)
- [shows up in search results](https://www.google.com/search?q="thank+you"+site%3Apartners.ubuntu.com).

What should happen: The page should be reachable only as the result of the relevant `POST`, not by merely visiting the URL.

[This is the sequel to [www.ubuntu.com#4523](https://github.com/canonical-websites/www.ubuntu.com/issues/4523).]

**Comment by anasereijo** [comment]
@nottrobin is this something base squad can help us with?

**Comment by pmahnke** [comment]
robots.txt?
