### ISSUE TITLE
Use latest canonicalwebteam/dev image in CI

### ISSUE THREAD

**Issue by jpmartinspt** [canonical-web-and-design/partners.ubuntu.com#229]
## Summary

CI fails with the latest canonicalwebteam/dev image. So we pinned the version we want to use in CircleCI.

## Expected

We should get to the bottom of why the CI is failing. 
From what I've seen it's likely an incompatibility between node 12 and node-sass.

**Comment by tbille** [comment]
Should be removed when partners moved.
